Task_1_2_1
1Alex4949031/OOP-Java- pull request #10
Opened 2022-09-28 08:44 UTC by 1Alex4949031

2022-10-03 11:10 UTC, shadrina requested changes

2022-10-03 11:10 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +  Stack(int size) {
Почему он не публичный?

2022-10-03 11:10 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +      this.increaseCapacity();
Здесь `this.` можно опустить

2022-10-03 11:10 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +      array[top] = null;
А вот это обязательно?

2022-10-03 11:10 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +  T[] popStack(int num) {
А почему возвращается массив, а не стек? В данном случае массив -- это часть внутренностей. Либо ничего не возвращай, либо цельный стек

2022-10-03 11:10 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +      newStack[i] = this.array[i];
`Arrays.copyOf`

2022-10-03 11:10 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +    this.size = this.size * 2;
1. this можно опускать, если нет клэша имен
2. Существует оператор `*=`

2022-10-04 04:41 UTC, 1Alex4949031 commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +  }
Исправил.

2022-10-04 04:43 UTC, 1Alex4949031 commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +      array[top] = null;
Нет, не обязательно, можно просто каждый раз менять top, но в данном случае считаю, что так более понятно и красиво.

2022-10-05 06:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +  void pushStack(Stack<T> st) {
Нет модификатора

2022-10-05 06:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +  Stack<T> popStack(int num) {
-

2022-10-05 06:04 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/a/seleznev/Stack.java
> +  private void increaseCapacity() {
Вниз

2022-10-05 10:49 UTC, 1Alex4949031 commented
Добавил Task_1_1_1 в ветку второй задачи, сейчас вроде все хорошо. Это же нормально, что в измененных файлах(files changed) только gradlew, верно ведь?

2022-10-11 18:23 UTC, shadrina requested changes
Нет, gradlew из первой задачи не должно меняться. Если меняется, скорее всего скопировал не ту версию. А почему варнинги в коде?

2022-10-12 06:58 UTC, closed without merging