Task_1_2_3
1Alex4949031/OOP-Java- pull request #13
Opened 2022-10-26 11:18 UTC by 1Alex4949031

2022-11-02 06:08 UTC, shadrina requested changes

2022-11-02 06:08 UTC, shadrina commented on Task_1_2_3/src/test/java/a/seleznev/nsu/GraphInputTests.java
> +    wr.close();
Try with resources

2022-11-02 06:08 UTC, shadrina commented on Task_1_2_3/src/test/java/a/seleznev/nsu/GraphInputTests.java
> +    File file = new File("src/test/resources/ListOfAdj.txt");
getResourceAsStream

2022-11-02 06:08 UTC, shadrina commented on Task_1_2_3/src/main/java/a/seleznev/nsu/Edge.java
> +public class Edge<T extends Comparable<T>> {
record

2022-11-02 06:08 UTC, shadrina commented on Task_1_2_3/src/main/java/a/seleznev/nsu/Graph.java
> +  private final HashMap<T, Vertex<T>> vertexes;
Map - интерфейс, HashMap - реализация

2022-11-02 06:08 UTC, shadrina commented on Task_1_2_3/src/main/java/a/seleznev/nsu/Graph.java
> +            throw new Error("Wrong matrix initialization!");
Чем отличается Error от Exception

2022-11-02 06:08 UTC, shadrina commented on Task_1_2_3/src/main/java/a/seleznev/nsu/Vertex.java
> +package a.seleznev.nsu;
ru.nsu.seleznev.a

2022-11-02 06:43 UTC, 1Alex4949031 commented on Task_1_2_3/src/main/java/a/seleznev/nsu/Graph.java
> +            throw new Error("Wrong matrix initialization!");
**Exceptions** — это, собственно, исключения: исключительная, незапланированная ситуация, которая произошла при работе программы.

**Error** — это критическая ошибка во время исполнения программы, связанная с работой виртуальной машины Java. В большинстве случаев Error не нужно обрабатывать, поскольку она свидетельствует о каких-то серьезных недоработках в коде.

В наших задачах мы обрабатываем исключительные ситуации.

2022-11-02 07:00 UTC, 1Alex4949031 commented on Task_1_2_3/src/main/java/a/seleznev/nsu/Edge.java
> +public class Edge<T extends Comparable<T>> {
**recored Edge<T extends Comparable<T>>(Vertex<T> start, Vertex<T> end, int weight)**{
 ...
}

2022-11-07 10:50 UTC, shadrina requested changes
В пул реквесте все еще много лишних файлов

2022-11-07 10:50 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/seleznev/a/Edge.java
> +public class Edge<T extends Comparable<T>> {
Я кстати уже говорила, что этот код эквивалентен `public record Edge(Vertex<T> start, Vertex<T> end, int weight)`?

2022-11-08 02:01 UTC, 1Alex4949031 commented on Task_1_2_3/src/main/java/ru/nsu/seleznev/a/Edge.java
> +public class Edge<T extends Comparable<T>> {
про record писали.

2022-11-08 02:05 UTC, 1Alex4949031 commented on Task_1_2_3/src/main/java/ru/nsu/seleznev/a/Vertex.java
> +public class Vertex<T extends Comparable<T>> {
Comparable используется для того, чтобы объекты можно было сравнить и сортировать в алгоритме Дейкстры.

2022-11-08 02:17 UTC, 1Alex4949031 commented on Task_1_2_3/src/test/java/ru/nsu/seleznev/a/GraphInputTests.java
> +    InputStream file = getClass().getClassLoader().getResourceAsStream("ListOfAdj.txt");
Хорошо, сейчас исправлю.

2022-11-08 02:34 UTC, 1Alex4949031 commented on Task_1_2_3/src/test/java/ru/nsu/seleznev/a/GraphInputTests.java
> +    try (Writer wr = new FileWriter("src/test/resources/ListOfAdjOutput.txt")) {
Запись будет произведена в файл ListOfAdjOutput.txt, который лежит в src/test/resources
Я попроверял, когда создается проект, то пути начинаются с папки этого проекта. Поэтому пути нужно указывать с src/.../.../...

2022-11-08 02:34 UTC, 1Alex4949031 commented on Task_1_2_3/src/test/java/ru/nsu/seleznev/a/GraphInputTests.java
> +    InputStream file = getClass().getClassLoader().getResourceAsStream("AdjacencyMatrix.txt");
Хорошо, понял

2022-11-08 08:09 UTC, shadrina commented on Task_1_2_3/src/test/java/ru/nsu/seleznev/a/GraphInputTests.java
> +    try (Writer wr = new FileWriter("src/test/resources/ListOfAdjOutput.txt")) {
А если JAR исполнить из какой-то другой директории?

2022-11-08 08:18 UTC, 1Alex4949031 commented on Task_1_2_3/src/test/java/ru/nsu/seleznev/a/GraphInputTests.java
> +    try (Writer wr = new FileWriter("src/test/resources/ListOfAdjOutput.txt")) {
Не получится вроде так, не найдет файл.

2022-11-09 05:59 UTC, shadrina commented
Леша, ну ты же умеешь смотреть на вкладку Files changed. Почему там куча всего лишнего?

2022-11-09 06:39 UTC, shadrina approved these changes

2022-11-09 06:56 UTC, merged