Task_1_4_1
1Alex4949031/OOP-Java- pull request #15
Opened 2022-11-24 15:06 UTC by 1Alex4949031

2022-11-24 15:20 UTC, 1Alex4949031 commented
![image](https://user-images.githubusercontent.com/91533963/203818596-f147e5ff-d715-484e-a805-389d3090e953.png)

2022-11-24 16:00 UTC, 1Alex4949031 commented
*Gradle ругается на switch case, еще почему-то ругался на jdk 14.0*

2022-11-25 07:21 UTC, 1Alex4949031 commented
**Исправил switch**

2022-11-29 14:08 UTC, shadrina requested changes

2022-11-29 14:08 UTC, shadrina commented on Task_1_4_1/src/main/java/ru/nsu/seleznev/a/CreditBookSemester.java
> +            || i.getMark().equals("Зачет"))).count() == marks.size();
Ага, он есть.. Тогда почему ты здесь строки сравниваешь?

2022-11-30 03:06 UTC, 1Alex4949031 commented on Task_1_4_1/src/main/java/ru/nsu/seleznev/a/StudentData.java
> +      System.out.println("С обычной стипендией в 1 семестре");
Добавил

2022-11-30 03:06 UTC, 1Alex4949031 commented on Task_1_4_1/src/main/java/ru/nsu/seleznev/a/CreditBookSemester.java
> +  }
Добавил

2022-11-30 03:07 UTC, 1Alex4949031 commented on Task_1_4_1/src/main/java/ru/nsu/seleznev/a/CreditBookSemester.java
> +            || i.getMark().equals("Зачет"))).count() == marks.size();
Да, согласен, изменил.

2022-12-08 11:38 UTC, shadrina approved these changes

2022-12-08 11:39 UTC, shadrina commented
А ты же на софт дедлайн ее показывал?

2022-12-08 12:08 UTC, 1Alex4949031 commented
Да, на софт дедлайн показывал.

2022-12-08 12:08 UTC, merged