Task_2_1_1
1Alex4949031/OOP-Java- pull request #18
Opened 2023-02-08 02:32 UTC by 1Alex4949031

2023-02-08 03:25 UTC, 1Alex4949031 commented
В тестах есть **собственное построение графика для исходной задачи** с использованием библиотеки **JChart**. Приложу сюда скриншот на всякий случай.
![image](https://user-images.githubusercontent.com/91533963/217421140-d483ef8b-8166-4c9a-b69a-08b45984288f.png)

2023-02-15 02:28 UTC, 1Alex4949031 commented
В тестах есть **собственное построение графика** для исходной задачи с использованием **библиотеки JChart**. Приложу сюда скриншот на всякий случай.
![image](https://user-images.githubusercontent.com/91533963/218911758-bc5cb78d-3136-4319-9ac2-8e4854e26b0c.png)

2023-02-15 03:29 UTC, 1Alex4949031 commented
_Отдельно про Threads:_

Фактически применение параллельных потоков сводится к тому, что данные в потоке будут разделены на части, каждая часть обрабатывается на отдельном ядре процессора, и в конце эти части соединяются, и над ними выполняются финальные операции. Рассмотрим некоторые критерии, которые могут повлиять на производительность в параллельных потоках:

Размер данных. Чем больше данных, тем сложнее сначала разделять данные, а потом их соединять.

Количество ядер процессора. Теоретически, чем больше ядер в компьютере, тем быстрее программа будет работать. Если на машине одно ядро, нет смысла применять параллельные потоки.

Чем проще структура данных, с которой работает поток, тем быстрее будут происходить операции. Например, данные из ArrayList легко использовать, так как структура данной коллекции предполагает последовательность несвязанных данных. А вот коллекция типа LinkedList - не лучший вариант, так как в последовательном списке все элементы связаны с предыдущими/последующими. И такие данные трудно распараллелить.

Над данными примитивных типов операции будут производиться быстрее, чем над объектами классов

4


Глядя на метод параллельного потока, вы можете задаться вопросом, откуда берутся потоки, используемые параллельным потоком, сколько их и как вы можете настроить процесс. Параллельные потоки внутренне используют значение по умолчанию ForkJoinPool, которое по умолчанию имеет столько потоков, сколько у вас есть процессоров, возвращаемых Runtime.getRuntime().availableProcessors(). Но вы можете изменить размер этого пула с помощью системного свойства java.util.concurrent.ForkJoinPool.common.parallelism.

Инфраструктура, используемая параллельными потоками за кулисами для параллельного выполнения операций, представляет собой инфраструктуру fork/join, представленную в Java 7. Очень важно иметь хорошее представление о внутренностях параллельных потоков, чтобы правильно их использовать. Платформа fork/join была разработана для рекурсивного разделения распараллеливаемой задачи на более мелкие задачи, а затем объединения результатов каждой подзадачи для получения общего результата. Это реализация интерфейса ExecutorService, который распределяет эти подзадачи между рабочими потоками в пуле потоков, который называется ForkJoinPool.

**Parallels stream:**

Расшифровывается Spliteratorкак «разделяемый итератор». Как и Итераторы, Разделители используются для обхода элементов источника, но они также предназначены для параллельного выполнения этих операций. Хотя на практике вам, возможно, не придется разрабатывать собственный Spliterator, понимание того, как это сделать, даст вам более широкое представление о том, как работают параллельные потоки.

Алгоритм, который разбивает поток на несколько частей, является рекурсивным процессом. На первом этапе вызываемый метод trySplitвызывается на первом Spliterator и генерирует второй. Затем на шаге 2 он снова вызывается для этих двух разветвителей, в результате чего получается четыре. Фреймворк продолжает вызывать метод trySplit для Spliterator до тех пор, пока он не вернет null, чтобы сигнализировать о том, что структура данных, которую он обрабатывает, больше не делится. Наконец, этот рекурсивный процесс разбиения завершается, когда все разветвители возвращают значение null при вызове trySplit

2023-02-21 07:56 UTC, shadrina requested changes

2023-02-21 07:56 UTC, shadrina commented on Task_2_1_1/src/main/java/nsu/seleznev/a/SequentialFinder.java
> +  public boolean finder(List<Long> numbers) {
У класса нет состояния => метод вполне мог бы быть статиком

2023-02-21 07:56 UTC, shadrina commented on Task_2_1_1/src/main/java/nsu/seleznev/a/SequentialFinder.java
> +    return  false;
Ну пробел лишний...

2023-02-21 07:56 UTC, shadrina commented on Task_2_1_1/src/main/java/nsu/seleznev/a/ParallelsStreamFinder.java
> +  public boolean parallelStreamApiFinder(List<Long> numbers) {
Аналогично тут логичнее сделать метод статик

2023-02-21 07:56 UTC, shadrina commented on Task_2_1_1/src/test/java/nsu/seleznev/a/ComplexTimeTest.java
> +    SequentialFinder test = new SequentialFinder();
Ну и тогда уйдут вот эти лишние создания инстансов

2023-02-21 08:16 UTC, 1Alex4949031 commented on Task_2_1_1/src/main/java/nsu/seleznev/a/SequentialFinder.java
> +    return  false;
Убрал)

2023-02-21 08:16 UTC, 1Alex4949031 commented on Task_2_1_1/src/main/java/nsu/seleznev/a/ParallelsStreamFinder.java
> +  public boolean parallelStreamApiFinder(List<Long> numbers) {
Понял, хорошо

2023-02-28 08:09 UTC, shadrina approved these changes

2023-02-28 08:09 UTC, shadrina commented on Task_2_1_1/src/main/java/nsu/seleznev/a/MultiThreadFinder.java
> +      }
Тут можно было обычным стримом

2023-02-28 08:09 UTC, 1Alex4949031 commented on Task_2_1_1/src/main/java/nsu/seleznev/a/MultiThreadFinder.java
> +      }
Хорошо, понял

2023-02-28 08:10 UTC, 1Alex4949031 commented on Task_2_1_1/src/main/java/nsu/seleznev/a/SequentialFinder.java
> +    return false;
Хорошо, понял

2023-02-28 08:10 UTC, merged